### ISSUE TITLE
PyCon Canada Twitter Account

### ISSUE THREAD

**Issue by dianaclarke** [pyconca/2012-web#1]
- Needs a logo
- Needs a bio

**Comment by nyap** [comment]
Bio added:

"Build a Canadian Python community. Work together to showcase Canadian talent at PyCon in Montreal in 2014 and 2015."

Edit if you want.

Taavi's rough logo: https://github.com/pyconca/pyconca/blob/master/assets/pycon.ca.svg

**Comment by nyap** [comment]
I wasn't able to open Taavi's logo in InkScape. If we just want a really basic placeholder logo, we could do something like this:

https://www.dropbox.com/gallery/27458944/1/pyconca?h=ee5d52

**Comment by wolever** [comment]
Weird. I can open Taavi's logo in Inkscape without issue. I've committed it here: https://github.com/pyconca/pyconca/blob/master/assets/pycon.ca.svg

And I'm using Inkscape 0.48.0 r9654.

**Comment by nyap** [comment]
Huh, that is weird. I'm using Inkscape 0.48.2 r9819 on a Mac. I can bug T about it later.

**Comment by nyap** [comment]
Talked to Taavi, and it was user error (aka my bad). We can talk about the logo at next meetup and vote on a winner if we think the current candidates (including Yi Qing's) are good enough.
