### ISSUE TITLE
Hosting pycon.ca

### ISSUE THREAD

**Issue by dianaclarke** [pyconca/2012-web#10]
I just signed up for vmfarms.com

I have no idea what I'm doing... might need help with this :)

**Comment by wolever** [comment]
Feel free to assign this one to me.

I'd vote: for now, I'll just throw it up the landing page on my VPS, then we can approach VMFarm to ask them for hosting once we've got something to show off.

**Comment by dianaclarke** [comment]
I've already paid for it. I have the domain, a really bad first pass at a landing page, and root access to the server. Now I just need help connecting the dots.

**Comment by eloraburns** [comment]
I've been wanting to figure out config management anyway, and http://saltstack.org/ is done in Python. I was at their BoF for a bit, and it's designed to do what Puppet does. :)

**Comment by dianaclarke** [comment]
We need to answer the following:

1) Please provide a list of users you would like. Please include: 
- User names 
- SSH Keys 
- Whether you would like sudo access for them 
- A password hash if you choose to use password based authentication 
- Any other options you would like

2) A list of domains and subdomains for your website or application. Please include: 
- The name of the domain and subdomain(s). If you need to purchase one, I highly recommend using GoDaddy (http://godaddy.com/) 
- SSL certificate if any. If you need to purchase one, I highly recommend using RapidSSL (http://www.rapidssl.com/)

3) Database names.

4) A description of your application's technologies. Please include: 
- The languages used (e.g. PHP, Ruby, Python, Java, etc...) 
- Any frameworks used (e.g. Ruby on Rails, Django, Cake, etc...) 
- What databases you are using (e.g. MySQL, Postgres, MongoDB, Redis, etc...) 
- Please also include existing database, usernames, and password hashes 
- Any other technologies (e.g. Memcache, RabbitMQ, etc...)

5) Will your app be sending mail?

6) Will you require DNS? If so, can you provide us with the domain to setup as well as any existing host names (i.e.: zone file)?

7) Any other useful information.

**Comment by wolever** [comment]
Oh… Looks like my email didn't make it though. Here it is:

> 1) Please provide a list of users you would like. Please include: 
> - User names 

wolever

> - SSH Keys 

ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAvyZUU3zNsAoETLN8kDgTmm6qPeWMqUno3KkxcayPSVzTU2pBLlMet/LVtLpHwqARTo4d5/g9vmjwPluQO7LgyIsH88GlJYRgPwV08rpzBTDR+/0ZQWt82J7loB1z6mhxMS+YS0Oe2UOEXxYTCKfwwyTXDKVRk8wjlneyI9JZfB8= wolever@wolever.local

> - Whether you would like sudo access for them 

yes.

> - A password hash if you choose to use password based authentication 

no password auth.

> 2) A list of domains and subdomains for your website or application. Please include: 
> - The name of the domain and subdomain(s). If you need to purchase one, I highly recommend using GoDaddy (http://godaddy.com/) 
> - SSL certificate if any. If you need to purchase one, I highly recommend using RapidSSL (http://www.rapidssl.com/)
>   3) Database names.
>   4) A description of your application's technologies. Please include: 
> - The languages used (e.g. PHP, Ruby, Python, Java, etc...) 
> - Any frameworks used (e.g. Ruby on Rails, Django, Cake, etc...) 
> - What databases you are using (e.g. MySQL, Postgres, MongoDB, Redis, etc...) 
> - Please also include existing database, usernames, and password hashes 
> - Any other technologies (e.g. Memcache, RabbitMQ, etc...)

Your call on the above.

If I was configuring the server, it would take me less time to install and configure all of the above than it would to have them install it then have to figure out their settings.

Also… Highly recommending GoDaddy? ಠ_ಠ

> 5) Will your app be sending mail?

Do they supply and SMTP server? If so, awesome — can we get the credentials?

Otherwise, if they want to configure Postfix or Exim for us, that'd be great. Otherwise, I can almost trivially do that.

> 6) Will you require DNS? If so, can you provide us with the domain to setup as well as any existing host names (i.e.: zone file)?

Assuming NameCheap is giving us DNS (it almost certainly is), we don't need it.

**Comment by hany55** [comment]
Hey Folks,

Hany from VM Farms here. No need to worry about configuring your servers. We do it all. All you need to worry about is writing code and deploying. We handle everything else. I'll work with Diana through our ticketing system. If anyone else needs help at all, please feel free to email us at support@vmfarms.com.

**Comment by kayzhu** [comment]
> Otherwise, if they want to configure Postfix or Exim for us, that'd be great. Otherwise, I can almost trivially do that.

I had some fights with Postfix (configuration and mostly "why is it marked as spam?" type of debug), so I'd be happy to try helping on this part too :) 

(also, please no GoDaddy :)
