### ISSUE TITLE
Contact Leila Boujnane, founder of Idée

### ISSUE THREAD

**Issue by nyap** [pyconca/2012-web#12]
From original "to do" list

Contact Leila Boujnane, founder of Idée about a "we are Toronto's tech" that she (apparently) started a while back.

Not sure who this should be assigned to.

**Comment by ysim** [comment]
I could do this. I'm relatively free these days.

**Comment by nyap** [comment]
Sure! Thanks for volunteering! Taavi said she had a bunch of content she was sitting on, so I'm interested in knowing if there's something blocking her from launching that we could try to find folks to help with, or if there are other factors.

**Comment by ysim** [comment]
Cool. Should I contact her directly or can somebody here make introductions?

**Comment by nyap** [comment]
Did anyone at the original meeting indicate that they knew her?

If not, the CEO at FreshBooks knows Taavi, Diana, and me and I'm sure he'd be happy to send an intro email on behalf of the group. Just lemme know and I'll nudge Taavi to talk to Mike.

**Comment by ysim** [comment]
Sounds good to me.
