### ISSUE TITLE
Contact Canadian Python groups

### ISSUE THREAD

**Issue by nyap** [pyconca/2012-web#3]
Canadian Python clubs
http://wiki.python.org/moin/LocalUserGroups#Canada

Canadian post-secondary
http://wiki.python.org/moin/SchoolsUsingPython#Canada
- Ask each club to select a rep to participate in planning? Or invite everyone to discussions?
- Encourage groups to start thinking about stuff they want to present or suggest awesome Canadians they think we should invite to present at PyCon

Reach out to companies that we know do coding in Python to spread the word as well.

**Comment by dianaclarke** [comment]
done-ish. for this year anyway
