### ISSUE TITLE
Get on PyCon Blog's "Pycon around the world"  list

### ISSUE THREAD

**Issue by ysim** [pyconca/2012-web#36]
Here: http://pycon.blogspot.ca/

**Comment by myusuf3** [comment]
You can assign this to me.

On Fri, Aug 17, 2012 at 3:25 PM, Yi Qing Sim notifications@github.comwrote:

> Here: http://pycon.blogspot.ca/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pyconca/pyconca/issues/36.

## 

Mahdi Yusuf

**Comment by wolever** [comment]
For some reason you aren't on the list of people the issue can be assigned to. But you can take this!

**Comment by dianaclarke** [comment]
I did already ask them to do this. They added us to most places already.
I'm not sure if they just missed this one, or if it's stuck in the queue
somewhere.

--diana

**Comment by myusuf3** [comment]
I think I need to be added as collaborator.

On Fri, Aug 17, 2012 at 3:37 PM, David Wolever notifications@github.comwrote:

> For some reason you aren't on the list of people the issue can be assigned
> to. But you can take this!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pyconca/pyconca/issues/36#issuecomment-7832822.

## 

Mahdi Yusuf

**Comment by myusuf3** [comment]
Jesse got back to me he is on it. He also needs the email of the person who is handling the blog posts he will give them access to the blog. 

What should I tell him? email wise.

**Comment by dianaclarke** [comment]
I would go with board@pycon.ca

Thanks!

--diana

**Comment by myusuf3** [comment]
It needs to be a google id. 

is boards@pycon.ca a google id?

## 

Mahdi

**Comment by nyap** [comment]
Yes. It's a Google apps address. David can clarify if it's just dist list email or a full account.

**Comment by myusuf3** [comment]
@wolever can you confirm?

**Comment by nyap** [comment]
@myusuf3 Taavi and I are pretty sure that if board@pycon.ca isn't a regular Google account with a login, it won't work. I don't have a way to confirm that though.

@wolever will have to confirm. If it's not an account with a login, then maybe we need something generic like info@ which is a regular Google account, but also forwards to board@

**Comment by myusuf3** [comment]
Lets do that then. Let me know what email it is.

On Sun, Aug 19, 2012 at 4:40 AM, Nicola Yap notifications@github.comwrote:

> @myusuf3 https://github.com/myusuf3 Taavi and I are pretty sure that if
> board@pycon.ca isn't a regular Google account with a login, it won't
> work. I don't have a way to confirm that though.
> 
> @wolever https://github.com/wolever will have to confirm. If it's not
> an account with a login, then maybe we need something generic like info@which is a regular Google account, but also forwards to board@
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/pyconca/pyconca/issues/36#issuecomment-7851510.

## 

Mahdi Yusuf

**Comment by wolever** [comment]
Ahh, sorry for the delay, guys. Have had a crazy last couple of days.

board@pycon.ca is an "apps group", not an actual apps account.

Ping me… anywhere… with the name you'd like to use (maybe pyconblog@pycon.ca?) and I'll create the account for you.

**Comment by nyap** [comment]
blog@pycon.ca is probably fine. It can just be our "blogger" identity for whatever blogging purposes we require.

Just let Madhi know when it's done.

**Comment by wolever** [comment]
Alright, done. @myusuf3: ping me on IRC and I'll send you the details.

**Comment by dianaclarke** [comment]
done
