### ISSUE TITLE
Update front page

### ISSUE THREAD

**Issue by merwok** [pyconca/2012-web#72]
Now that PyCon CA 2012 is past (no), maybe the root page should be updated to say that it’s done, and link to http://pyvideo.org/category/25/pycon-ca-2012

**Comment by dianaclarke** [comment]
Good point, merwork!

I added a quick link to the videos on the main page: http://2012.pycon.ca/

We can do something nicer later, but I wanted it live for the Montreal Python meetup tonight.

Wish I was there! I'm sure you'll rock it!

Thanks!

--diana

**Comment by merwok** [comment]
Thanks :)
