### ISSUE TITLE
Define stuff to put on pycon.ca

### ISSUE THREAD

**Issue by nyap** [pyconca/2012-web#8]
So we have pycon.ca - What are we going to put on the site?

Some ideas from the Montreal Python wiki (damn those guys are organized). Some annoying troll has been messing with content on some of the actual pages in the last few days, but the overall list of stuff they have is a good start.
http://wiki.montrealpython.org/wiki/Main_Page

What we have now:
- Email account
- Twitter
- github
- pycon.ca domain
- IRC
- Google Group

**Comment by dianaclarke** [comment]
I'm working in this. I'll place it on a simple placeholder page.

**Comment by dianaclarke** [comment]
done
